name: cargo update

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Europe/Stockholm

jobs:
  build:
    uses: blackportal-ai/infra/.github/workflows/cargo-update.yml@master
    secrets: inherit
