name: core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/CONTRIBUTING.md"
      - "**/.gitignore"
      - "**/.github/ISSUE_TEMPLATE/**"
      - "**/.config/**"

jobs:
  core:
    uses: blackportal-ai/infra/.github/workflows/core.yml@master
    secrets: inherit
