name: core

on:
  push:
    branches:
      - reusable-workflow
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/CONTRIBUTING.md"
      - "**/.gitignore"
      - "**/.github/ISSUE_TEMPLATE/**"
      - "**/.config/**"

jobs:
  clippy:
    uses: blackportal-ai/infra/.github/workflows/core.yml@master
    secrets: inherit

  #build:
  #  uses: blackportal-ai/infra/.github/workflows/core.yml@master
  #  secrets: inherit

  #test:
  #  uses: blackportal-ai/infra/.github/workflows/core.yml@master
  #  secrets: inherit

  #coverage:
  #  uses: blackportal-ai/infra/.github/workflows/core.yml@master
  #  secrets: inherit
